enquete/urls.py
from django.urls import path
from . import views

app_name='enquete'
urlpatterns = [
	path('', views.index, name='index'),
	path('<int:id_pergunta>/', views.detalhes, name='detalhes'),
	path('<int:id_pergunta>/resultados', views.resultados, name='resultados'),
	path('<int:id_pergunta>/votacao', views.votacao, name='votacao'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('enquete/', include('enquete.urls')),
    path('admin/', admin.site.urls),
]

enquete/models.py
import datetime
from django.db import models
from django.utils import timezone

class Pergunta(models.Model):
	texto = models.CharField(max_length=200)
	data_pub = models.DateTimeField('Data de publicação')
	def __str__(self):
		return self.texto
	def publicada_recentemente(self):
		return self.data_pub >= timezone.now() - datetime.timedelta(days=1)

class Opcao(models.Model):
	pergunta = models.ForeignKey(Pergunta, 
						on_delete=models.CASCADE)
	texto = models.CharField(max_length=200)
	votos = models.IntegerField(default=0)
	def __str__(self):
		return self.texto

enquete/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from .models import Pergunta

# Create your views here.
def index(request):
	ultimas_perguntas = Pergunta.objects.order_by('-data_pub')[:5]
	contexto = {'ultimas_perguntas': ultimas_perguntas}
	return render(request, 'enquete/index.html', contexto)

def detalhes(request, id_pergunta):
	pergunta = get_object_or_404(Pergunta, pk=id_pergunta)
	return render(request, 'enquete/detalhes.html', {'pergunta':pergunta})

def resultados(request, id_pergunta):
	resposta = "Apresentação dos resultados da pergunta %s."
	return HttpResponse(resposta % id_pergunta)

def votacao(request, id_pergunta):
	resposta = "Votação para a questão %s."
	return HttpResponse(resposta % id_pergunta)

enquete/templates/enquete/detalhes.html
<!DOCTYPE html>
<html lang="pt-br" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Enquetes</title>
  </head>
  <body>
    <h1>Aplicação de Enquetes</h1>
    <h3><u>Pergunta</u>: {{ pergunta.texto }}</h3>
    {% if error_message %}
      <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <form action="{% url 'enquete:votacao' pergunta.id %}" method="post">
      {% csrf_token %}
      {% for opcao in pergunta.opcao_set.all %}
        <input type="radio" name="opcao" id="opcao{{ forloop.counter }}" value="{{ opcao.id }}">
        <label for="opcao{{ forloop.counter }}">
          {{ opcao.texto }}</label><br/>
      {% endfor %}
      <input type="submit" value="Votar">
    </form>
  </body>
</html>

enquete/templates/enquete/index.html
<!DOCTYPE html>
<html lang="pt-br" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Enquetes</title>
  </head>
  <body>
    <h1>Aplicação de Enquetes</h1>
    <h2>Lista das Últimas Perguntas</h2>
    {% if ultimas_perguntas %}
      <ul>
        {% for pergunta in ultimas_perguntas %}
          <li><a href="{% url 'enquete:detalhes' pergunta.id %}">
            {{ pergunta.texto }}
          </a></li>
        {% endfor %}
      </ul>
    {% else %}
      <p>Nenhuma pergunta cadastrada.</p>
    {% endif %}
  </body>
</html>